Adding support for multi-value profiling using filterin and filterout elements
toasttab/xslt10-stylesheets pull request #4
Opened 2020-01-08 21:10 UTC by nvijaybhaskar-toast

This PR updates the `effectivity.xsl` stylesheet with logic required to support `filterin` and `filterout` elements whose attributes may have multiple values separated using a user-defined delimiter. 

A module or structure containing a `filterout` element whose effectivity attribute(s) has one or more values separated by a user-defined delimiter (e.g. a semicolon or a pipe), the processor only excludes the module or structure if least one effectivity attribute value exactly matches the effectivity parameter value passed to the stylesheet.  

A module or structure containing a `filterin` element whose effectivity attribute(s) has one or more values separated by a user-defined delimiter (e.g. a semicolon or a pipe), the processor only includes the modules if at least one effectivity attribute value exactly matches the effectivity parameter value passed to the stylesheet.

2020-02-07 15:01 UTC, pdesjardins commented on xsl/assembly/effectivity.xsl
> +      <xsl:call-template name="cross.compare">
My processor goes into what seems to be an infinite loop here, if I set `effectivity.arch`. Let's take a look at my test setup?

2020-02-10 04:10 UTC, pdesjardins requested changes
This looks like a great way to use the cross.compare template to accept multiple, delimited strings in an effectivity parameter.

- We should set a default value for `effectivity.separator` so that the templates work when no custom separator is specified.
- The variable elements should only call `cross.compare` if an effectivity attribute is present on the filterout or filterin element being evaluated. We need some way to avoid returning `true` if an empty string effectivity parameter matches an empty string effectivity attribute.

2020-02-10 04:10 UTC, pdesjardins commented on xsl/assembly/effectivity.xsl
> +  <xsl:param name="effectivity.separator" />
Set a default value so that the `cross.compare` template will work even if a user does not specify a value.

```
<xsl:param name="effectivity.separator">;</xsl:param>
```

2020-02-10 04:10 UTC, pdesjardins commented on xsl/assembly/effectivity.xsl
> +      <xsl:call-template name="cross.compare">
We're seeing this return `1` when an effectivity parameter is not set (which is usually the case) and the matching effectivity attribute is not set (also usually the case). Empty string equals empty string so the cross.compare template returns `1`. Since the `when` conditions below are testing for `1`, filterout elements always filter modules out.

Maybe wrap the `call-template` to cross.compare in an `xsl:if` element that tests for the effectivity attribute being set on the filterout/filterin elements?

```
    <xsl:variable name="effectivity.match.arch">
      <xsl:if test="@arch">
        <xsl:call-template name="cross.compare">
          <xsl:with-param name="a" select="$effectivity.arch" />
          <xsl:with-param name="b" select="@arch" />
        </xsl:call-template>
      </xsl:if>
    </xsl:variable>
```

This way, if the filterout/filterin element doesn't have a value in its effectivity attribute, we don't call the test template at all.

2020-02-10 04:10 UTC, pdesjardins commented on xsl/assembly/effectivity.xsl
> +      <xsl:when test="$effectivity.match.arch != ''">
This should work just fine, because if the `effectivity.arch` parameter is `foo` and the filterout element `arch` attribute is set to `foo`, cross.compare will return `1` and this when test will return `true`.

But would the test be a little tighter and more definitive by testing for the exact string `1`?

Like this?

```
      <xsl:when test="$effectivity.match.arch = '1'">
        <xsl:text>exclude</xsl:text>       
```

2020-02-10 04:10 UTC, pdesjardins commented on xsl/assembly/effectivity.xsl
> +      <xsl:call-template name="cross.compare">
Like the filterout variables, these will all be set to `1` when neither one of an effectivity parameter and its corresponding effectivity attribute are set at all. I'd wrap the call to cross.compare in an xsl:if element.

2020-02-21 15:24 UTC, nvijaybhaskar-toast commented on xsl/assembly/effectivity.xsl
> +  <xsl:param name="effectivity.separator" />
Done!

2020-02-21 20:49 UTC, nvijaybhaskar-toast commented on xsl/assembly/effectivity.xsl
> +      <xsl:when test="$effectivity.match.arch != ''">
I would certainly feel more comfortable testing for the exact string. However, I recall we had a conversation about not taking that approach as some users might want to use a different string. 

That said, I think we can make a reasonable assumption that your average Docbook user is not going to want to change the string. If indeed someone wants to change it, we can consider them a power user and assume that they would expect this change to have a butterfly effect. 

Does that sound like a reasonable assumption? If yes, I'm happy to change the test to the string `1`

2020-02-21 20:56 UTC, nvijaybhaskar-toast commented on xsl/assembly/effectivity.xsl
> +      <xsl:call-template name="cross.compare">
Done!

2020-02-24 18:39 UTC, nvijaybhaskar-toast commented on xsl/assembly/effectivity.xsl
> +      <xsl:call-template name="cross.compare">
Done!

2020-02-26 16:57 UTC, nvijaybhaskar-toast commented on xsl/assembly/effectivity.xsl
> +      <xsl:when test="$effectivity.match.arch != ''">
Closing the loop here - we had a conversation and decided that testing for the string `1` is fine. Made changes across the file.

2020-04-13 17:32 UTC, pdesjardins approved these changes
👍

2020-04-13 17:32 UTC, merged